#%RAML 0.8
---
title: Test API
baseUri: https://test.raml.net/api/{version}
version: v1
mediaType:  application/json
resourceTypes:
  - collection:
      get:
        responses:
          200:
            body:
  - collection-item:
      get:
        responses:
          200:
            body:

/:
  type: collection
  get:
  /test:
    type: collection
    get:
    /subTest:
      type: collection
      get:
      /item:
        type: collection-item
        get:
